### ISSUE TITLE
Create Kedro Academy materials to reinforce learning: exercise and quizzes

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#14]
This is a child task of kedro-org/kedro-devrel#13 and covers creation of materials to help reinforce the learnings:

* An exercise (details TBD)
* A set of Slido or Mentimeter quizzes

**Comment by astrojuanlu** [comment]
I ended up introducing more diverse exercises and deviating a bit from the kedro-university example. For some of the sections it was "too easy", and it looks like we will have a quite capable audience for the first edition, so I resorted to more challenging exercises that are independent from one another. For some others, I adapted the kedro-university example to be more self-contained and not so dependant on the Kedro directory structure, since the Replit UI doesn't scale really well for lots of files and directories.

I'm open to revisiting this in future editions though - there's a chance that having a single central thread throughout the course makes it more appealing than having a bunch of disconnected exercises.

For now, closing this ticket.
