### ISSUE TITLE
Explore further how to deliver exercises using collaborative coding environments

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#35]
Following our first training session we need to review whether Replit is the best option for collaborative coding exercises

**Comment by astrojuanlu** [comment]
Gitpod is based on VS Code, has a good free tier https://www.gitpod.io/pricing/ (25 to 50 hours per month per user for free, which is more than enough for our course) and it allows live collaboration https://www.gitpod.io/docs/configure/workspaces/collaboration#sharing-running-workspaces and it also supports third party tools like https://git.live/pricing (free for up to 5 users).

GitHub Codespaces is not free and the advantages are minor (access to the privative plugins), so I think it's disqualified.

For the autograding, we could set up some normal pytest test cases and ask them to validate their results. Since it's impractical to evaluate students submissions _during_ the course, there's no need for immediate feedback anyway.

**Comment by yetudada** [comment]
What was the resolution on the Anaconda teaching tool?

**Comment by astrojuanlu** [comment]
@yetudada Anaconda Notebooks is primarily based on JupyterLab. It has a somewhat restricted, but nonetheless useful, free tier (500 daily CPU seconds), however if we want to focus more on VS Code, it's probably not the best option. Notice that on Gitpod we can still open `.ipynb` files using the native VS Code notebook integration, or even install JupyterLab and launch it as a web service.

**Comment by astrojuanlu** [comment]
Some Gitpod inspiration:

- https://github.com/kedro-org/kedro/blob/main/.gitpod.yml
- https://github.com/noklam/kedro-starters/blob/main/.gitpod.yml

**Comment by astrojuanlu** [comment]
https://github.com/kedro-org/kedro-academy/pull/9 ready for final review

**Comment by astrojuanlu** [comment]
Just for the record, I think I misunderstood the GitHub Codespaces pricing cc @stichbury, there seem to be a free tier indeed:

https://github.com/features/codespaces

![image](https://user-images.githubusercontent.com/316517/225631846-4c6d5651-b3b2-4558-8b4c-46c87b4010ca.png)

We'll use Gitpod this time, but I'm open to revisiting this decision if we see a significant advantage of using GH Codespaces.

**Comment by astrojuanlu** [comment]
Another point in favor of GitHub Codespaces: they support JupyterLab https://github.blog/changelog/2022-11-09-using-codespaces-with-jupyterlab-public-beta/, https://docs.github.com/en/codespaces/developing-in-codespaces/getting-started-with-github-codespaces-for-machine-learning

whereas Gitpod requires manual configuration https://github.com/gitpod-io/gitpod/issues/16306

**Comment by astrojuanlu** [comment]
For the record, I quickly evaluated GH Codespaces again with JupyterLab, and it felt clunky and unreliable to be honest. Sticking to Gitpod for the time being.
