### ISSUE TITLE
Create a new blog post for Kedro-Viz

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#76]
### Context
Create a new blog post highlighting what Kedro-Viz is, what problem it solves and how it does it (features).

### Goal
The goal is to write a blog post to increase awareness and adoption of Kedro-Viz.
Audience are non-technical users.

**Comment by stichbury** [comment]
Hi @NeroOkwa I like this idea but I think it needs more focus before you start writing, to ensure it's a useful read that goes beyond looking at GitHub or documentation. For example, it could be "Five features of Kedro-Viz to show off your data science project" or "How to debug a failing workflow" or something.

I think we need to iterate on a brief here to decide what content to include. So that would be something along the lines of this:

# Proposed brief

## Introduction
* What is the problem this blog post solves?
* Who will find this information useful
* What titles would you choose? What keywords are you trying to hit (I can help with this)?

## Narrative subsections
* List each of the subsections of the post and what each one covers

## Conclusion
* Why the reader is now better off -- what have you explained? How would you promote this text in a tweet or linkedin post (think of this text first, and work back if it helps).

**Comment by astrojuanlu** [comment]
Unsure what's the value this would add at this point. Better to keep highlighting new features as we've been doing in #129 and others.
