### ISSUE TITLE
Publish a four-part mini-blog series about Notebook issues and how Kedro can resolve them 

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#80]
This picks up from where [#2461](https://github.com/kedro-org/kedro/issues/2461) began as a four-part mini-blog series about issues a Notebook user might experience and how Kedro can resolve them.

There may ultimately be a fifth section which pulls each together and creates an über-post of "How to use Kedro to ease yourself out of the pain of Notebooks" but that's TBD. This ticket covers the creation, publication and distribution of the four posts by @amandakys

**Comment by astrojuanlu** [comment]
Super excited about this 🙌🏽  and happy to brainstorm or collaborate in any way!

**Comment by stichbury** [comment]
I have made a set of changes over on Notion and this is now ready for review and feedback from @astrojuanlu and potentially @noklam if time, and then final readthrough by @amandakys to ensure she's happy with the final edit.

Juan Luis and I have scheduled time on 2nd Oct for this given our schedules in coming days, so this will be on hold until then.

**Comment by noklam** [comment]
I have dropped a few comments in the notes. I am thinking instead of showing all the rough edges of Kedro and unstable component (ConfigLoader). Should we just switch to OmegaConfigLoader and wait until some of the changes are in-place? It's nice to explain to our user what they may need to change, better if they don't even have to!

This also depends on the plan to release this series, do we have a rough target date?

These tickets are going to affect this series:
- https://github.com/kedro-org/kedro/issues/2971
- https://github.com/kedro-org/kedro/issues/2967
- https://github.com/kedro-org/kedro/issues/2965

**Comment by astrojuanlu** [comment]
Closing this one, since the blog post was published already https://kedro.org/blog/add-kedro-to-your-data-science-notebook
